2019-04-05 10:28:54,573 [MainThread] [INFO]  Program start.
2019-04-05 10:28:57,632 [WorkerThread1] [INFO]  Catch message: {'content_type': 'text', 'message_id': 119, 'from_user': {'id': 116078429, 'is_bot': False, 'first_name': 'Serious', 'username': 'serious_radish', 'last_name': 'Radish', 'language_code': 'ru'}, 'date': 1554449272, 'chat': {'type': 'private', 'last_name': 'Radish', 'first_name': 'Serious', 'username': 'serious_radish', 'id': 116078429, 'title': None, 'all_members_are_administrators': None, 'photo': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'sticker_set_name': None, 'can_set_sticker_set': None}, 'forward_from_chat': None, 'forward_from': None, 'forward_date': None, 'reply_to_message': None, 'edit_date': None, 'media_group_id': None, 'author_signature': None, 'text': 'vasa', 'entities': None, 'caption_entities': None, 'audio': None, 'document': None, 'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None, 'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None, 'connected_website': None, 'json': {'message_id': 119, 'from': {'id': 116078429, 'is_bot': False, 'first_name': 'Serious', 'last_name': 'Radish', 'username': 'serious_radish', 'language_code': 'ru'}, 'chat': {'id': 116078429, 'first_name': 'Serious', 'last_name': 'Radish', 'username': 'serious_radish', 'type': 'private'}, 'date': 1554449272, 'text': 'vasa'}}.
2019-04-05 10:29:18,636 [WorkerThread2] [INFO]  User @serious_radish (user id is 116078429) send /reg.
2019-04-05 10:29:36,250 [WorkerThread1] [ERROR]  TypeError occurred, args=("reply_to() got multiple values for argument 'message'",)
Traceback (most recent call last):
  File "/Users/owl/Pycharm/PycharmProjects/im_last_bot/venv/lib/python3.7/site-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/Users/owl/Pycharm/PycharmProjects/im_last_bot/tiny_client/test_another_pytelegrambotapi.py", line 79, in get_name
    bot.reply_to(message, message=to_send)
TypeError: reply_to() got multiple values for argument 'message'

